--Phases of Exploratory Data Analysis in SQL

----1. Database Exploration(Understanding Tables and Column Schema of the Database before working on the data)
-- Explore all Objects in Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all Columns in Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

------------------------------------------------------------------------------------

----2. Dimension Exploration(Identifying the unique values(Categories) in each dimension. The helps in recognizing how data might be grouped or segmented. which is useful for later analysis)

--Explore all countries our customers come from
SELECT DISTINCT Country FROM gold.dim_customers

--Explore all Categories "The Major Division"
SELECT DISTINCT Category,subcategory,product_name FROM gold.dim_products 
ORDER BY 1,2,3

------------------------------------------------------------------------------------

----3. Date Exploration(Identify the data boundaries(Earliest and Latest date) helping us understand the scope of data and the timespan 

--Find the date of First and Last Order
SELECT MIN(order_date) as Earliest_Order_Date,
MAX(order_date) as Latest_Order_Date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS Year_Diff
FROM gold.fact_sales

--Find the Youngest and Oldest Customer
SELECT MIN(birthdate) as Oldest_Customer_birthdate,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS Old_Age,
MAX(birthdate) as Youngest_Customer_birthdate,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS Young_Age,
DATEDIFF(YEAR,MIN(birthdate),MAX(birthdate)) AS Age_Diff
FROM gold.dim_customers

--------------------------------------------------------------------------------------

----4. Measure Exploration(Calculating the key metrics of Business - Highest level of Aggregation | Lowest level of Details)
--Find the Total Sales
SELECT SUM(sales_amount) as Total_Sales from gold.fact_sales

--Find how many items were sold
SELECT SUM(quantity) as Total_Quantity from gold.fact_sales

--Find the average selling price
SELECT AVG(price) as Avg_Price from gold.fact_sales

--Find the total number of orders
SELECT COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales

--Find the total number of Products
SELECT COUNT(DISTINCT product_key) as total_products FROM gold.dim_products

--Find the total number of customers
SELECT COUNT(DISTINCT customer_key) as total_customerss FROM gold.dim_customers

--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) as total_customerss FROM gold.fact_sales

--Generate a report that shows all metrics of the business
SELECT 'Total Sales' as KPI, SUM(sales_amount) as KPI_Output from gold.fact_sales
UNION ALL
SELECT 'TotalQuantity' as KPI,SUM(quantity) as KPI_Output from gold.fact_sales
UNION ALL
SELECT 'Average Price' as KPI,AVG(price) as KPI_Output from gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' as KPI,COUNT(DISTINCT order_number) as KPI_Output FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' as KPI,COUNT(DISTINCT product_key) as KPI_Output FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers' as KPI,COUNT(DISTINCT customer_key) as KPI_Output FROM gold.dim_customers
UNION ALL
SELECT 'Total Nr. Customers Who Ordered' as KPI,COUNT(DISTINCT customer_key) as KPI_Output FROM gold.fact_sales

-----------------------------------------------------------------------------------------------------

----5. Magnitude Analysis(Compare the meassure values with different categories to understand importance of categories)

--Find Total Customers by Countries
SELECT COUNT(DISTINCT customer_key) as 'Total Customers', Country FROM gold.dim_customers GROUP BY Country ORDER BY 'Total Customers' DESC

--Find Total Customers by Gender
SELECT COUNT(DISTINCT customer_key) as 'Total Customers', Gender FROM gold.dim_customers GROUP BY Gender ORDER BY 'Total Customers' DESC

--Find Total Products by Category
SELECT COUNT(DISTINCT Product_key) as 'Total Products', Category FROM gold.dim_products GROUP BY Category ORDER BY 'Total Products' DESC

--What is the Average costs in each category?
SELECT AVG(cost) as 'Average Costs', Category FROM gold.dim_products GROUP BY Category ORDER BY 'Average Costs' DESC

--What is the total revenue generated for each category?
SELECT b.Category,
SUM(a.sales_amount) as 'Total Revenue'
FROM gold.fact_sales a LEFT JOIN gold.dim_products b
on a.product_key=b.product_key
GROUP BY b.category
ORDER BY 'Total Revenue' DESC

--Find total revenue generated by each customer
SELECT b.first_name, b.last_name,SUM(a.sales_amount) as 'Total Revenue'
FROM gold.fact_sales a LEFT JOIN gold.dim_customers b
on a.customer_key=b.customer_key
GROUP BY b.customer_key,b.first_name,b.last_name
ORDER BY 'Total Revenue' DESC

--What is the distribution of sold items across countries?
SELECT b.country,SUM(a.quantity) as 'Total Quantity'
FROM gold.fact_sales a LEFT JOIN gold.dim_customers b
on a.customer_key=b.customer_key
GROUP BY b.country
ORDER BY 'Total Quantity' DESC

-----------------------------------------------------------------------------------------------------

----6. Ranking Analysis(Order the bvalues of dimensions to identify the Top/Bottom Performers)

--Which 5 Products generate the higher Revenue?
--Method 1(TOP and Group By)
SELECT TOP 5 b.Product_Name as Product,
SUM(a.Sales_amount) as Revenue
FROM gold.fact_sales a LEFT JOIN gold.dim_products b
on a.product_key=b.product_key
GROUP BY b.Product_Name
ORDER BY Revenue DESC

--Method 2(Window Functions and CTE - You can also do Subquery)
WITH CTE AS
(
SELECT b.Product_Name as Product,
SUM(a.Sales_amount) as Revenue,
ROW_NUMBER() OVER (ORDER BY SUM(a.sales_amount) DESC) AS Top_Rank
FROM gold.fact_sales a LEFT JOIN gold.dim_products b
on a.product_key=b.product_key
GROUP BY b.Product_Name
)
SELECT * FROM CTE WHERE Top_Rank<=5

--Which 5 Products generate the lowest Revenue?
--Method 1(TOP and Group By)
SELECT TOP 5 b.Product_Name as Product,
SUM(a.Sales_amount) as Revenue
FROM gold.fact_sales a LEFT JOIN gold.dim_products b
on a.product_key=b.product_key
GROUP BY b.Product_Name
ORDER BY Revenue ASC

--Method 2(Window Functions and Subquery)
WITH CTE AS
(
SELECT b.Product_Name as Product,
SUM(a.Sales_amount) as Revenue,
ROW_NUMBER() OVER (ORDER BY SUM(a.sales_amount) ASC) AS Top_Rank
FROM gold.fact_sales a LEFT JOIN gold.dim_products b
on a.product_key=b.product_key
GROUP BY b.Product_Name
)
SELECT * FROM CTE WHERE Top_Rank<=5

---Find the top 10 customers who have generated the highest revenue
WITH CTE AS
(
SELECT b.first_name,b.last_name,
SUM(a.Sales_amount) as Revenue,
ROW_NUMBER() OVER (ORDER BY SUM(a.sales_amount) DESC) AS Top_Rank
FROM gold.fact_sales a LEFT JOIN gold.dim_customers b
on a.customer_key=b.customer_key
GROUP BY b.customer_key,b.first_name,b.last_name
)
SELECT * FROM CTE WHERE Top_Rank<=10

---------------------------------------------------------------------------------------------------------------------

--EDA Completed